namespace:
  create: true
  name: llm-observability-validation
monitoring:
  enabled: false
ollamaModel:
  enabled: false
ollama:
  enabled: false
openWebUI:
  enabled: false
open-webui:
  enabled: false
redis:
  enabled: false
ollamaGateway:
  enabled: false
edgeToolbox:
  enabled: false
otelTraceSeeder:
  enabled: false
etcd:
  enabled: false
