{{- if and .Values.openWebUI.enabled (not .Values.openWebUI.existingSecret) .Values.openWebUI.webuiSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: {{ include "llm-observability-stack.namespace" . }}
type: Opaque
stringData:
  {{ .Values.openWebUI.existingSecretKey }}: {{ .Values.openWebUI.webuiSecretKey | quote }}
{{- end }}
