import json
import os
import time
from datetime import datetime, timedelta, timezone
from typing import Any
from uuid import UUID, uuid4

import requests
from langsmith import Client

DEFAULT_API_URL = "http://ollama:11434/api/chat"
DEFAULT_MODEL = "gemma3-1b-it-gguf-local"
DEFAULT_PROJECT = "k3s-ollama-gemma-local"
DEFAULT_ENDPOINT = "https://api.smith.langchain.com"
DEFAULT_TIMEOUT_SECONDS = 180
DEFAULT_CALL_COUNT = 12
DEFAULT_FEEDBACK_KEY = "response_quality"
SCRIPT_TAG = "observability-seed"

DEFAULT_PROMPTS = [
    "Explain what Kubernetes readiness probe means in one short paragraph.",
    "Give one example where GPU acceleration helps inference latency.",
    "What is LangSmith used for in LLM observability workflows?",
    "Write three bullet points for debugging Ollama in k3s.",
]


def get_required_api_key() -> str:
    api_key = os.getenv("LANGSMITH_API_KEY") or os.getenv("LANGCHAIN_API_KEY")
    if not api_key:
        raise SystemExit("LANGSMITH_API_KEY or LANGCHAIN_API_KEY is not set")
    return api_key


def load_prompts() -> list[str]:
    raw_json = os.getenv("OBS_PROMPTS_JSON")
    if raw_json:
        try:
            payload = json.loads(raw_json)
        except json.JSONDecodeError as exc:
            raise SystemExit(f"OBS_PROMPTS_JSON is not valid JSON: {exc}") from exc
        if not isinstance(payload, list) or not all(isinstance(item, str) and item.strip() for item in payload):
            raise SystemExit("OBS_PROMPTS_JSON must be a non-empty JSON array of strings")
        return [item.strip() for item in payload]

    raw_split = os.getenv("OBS_PROMPTS")
    if raw_split:
        prompts = [item.strip() for item in raw_split.split("||") if item.strip()]
        if prompts:
            return prompts

    return list(DEFAULT_PROMPTS)


def extract_answer(payload: dict[str, Any]) -> str:
    message = payload.get("message")
    if isinstance(message, dict):
        content = message.get("content")
        if isinstance(content, str):
            return content

    response = payload.get("response")
    if isinstance(response, str):
        return response

    return json.dumps(payload, ensure_ascii=True)[:1500]


def score_response(answer: str, had_error: bool) -> float:
    if had_error:
        return 0.0
    tokens = len(answer.split())
    if tokens < 3:
        return 0.25
    if tokens < 10:
        return 0.6
    return 1.0


def create_run(client: Client, run_id: UUID, project: str, prompt: str, model: str, api_url: str) -> None:
    client.create_run(
        id=run_id,
        name="ollama_proxy_inference",
        run_type="llm",
        project_name=project,
        start_time=datetime.now(timezone.utc),
        inputs={
            "prompt": prompt,
            "model": model,
            "inference_api_url": api_url,
            "stream": False,
        },
        tags=["k3s", "ollama", "langsmith", SCRIPT_TAG],
    )


def update_success_run(
    client: Client,
    run_id: UUID,
    status_code: int,
    elapsed_ms: float,
    answer: str,
    raw_payload: dict[str, Any],
) -> None:
    client.update_run(
        run_id=run_id,
        end_time=datetime.now(timezone.utc),
        outputs={
            "status_code": status_code,
            "latency_ms": round(elapsed_ms, 2),
            "answer": answer,
            "answer_preview": answer[:500],
            "response_done": raw_payload.get("done"),
        },
    )


def update_error_run(client: Client, run_id: UUID, status_code: int | None, elapsed_ms: float, error: str) -> None:
    payload: dict[str, Any] = {"latency_ms": round(elapsed_ms, 2)}
    if status_code is not None:
        payload["status_code"] = status_code
    client.update_run(
        run_id=run_id,
        end_time=datetime.now(timezone.utc),
        outputs=payload,
        error=error,
    )


def create_feedback(client: Client, run_id: UUID, key: str, answer: str, had_error: bool) -> None:
    score = score_response(answer, had_error)
    comment = "auto-generated by python-toolbox/langsmith_inference_traces.py"
    client.create_feedback(
        run_id=run_id,
        key=key,
        score=score,
        comment=comment,
    )


def recent_seeded_runs(client: Client, project: str, lookback_minutes: int = 30) -> list[Any]:
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=lookback_minutes)
    items = list(client.list_runs(project_name=project, start_time=cutoff, limit=100))
    return [item for item in items if SCRIPT_TAG in (getattr(item, "tags", None) or [])]


def seed_inference_runs(
    client: Client,
    project: str,
    model: str,
    api_url: str,
    timeout_seconds: int,
    call_count: int,
    feedback_key: str,
    prompts: list[str],
) -> tuple[int, int, int]:
    success = 0
    failures = 0

    for index in range(call_count):
        prompt = prompts[index % len(prompts)]
        run_id = uuid4()

        create_run(client, run_id, project, prompt, model, api_url)

        status_code: int | None = None
        answer = ""
        started = time.perf_counter()

        try:
            response = requests.post(
                api_url,
                json={
                    "model": model,
                    "stream": False,
                    "messages": [{"role": "user", "content": prompt}],
                },
                timeout=(10, timeout_seconds),
            )
            status_code = response.status_code
            response.raise_for_status()
            payload = response.json()
            answer = extract_answer(payload)
            elapsed_ms = (time.perf_counter() - started) * 1000

            update_success_run(client, run_id, status_code, elapsed_ms, answer, payload)
            create_feedback(client, run_id, feedback_key, answer, had_error=False)
            success += 1
            print(f"[{index + 1}/{call_count}] OK run_id={run_id} latency_ms={elapsed_ms:.2f}")
        except Exception as exc:
            elapsed_ms = (time.perf_counter() - started) * 1000
            update_error_run(client, run_id, status_code, elapsed_ms, str(exc))
            create_feedback(client, run_id, feedback_key, answer, had_error=True)
            failures += 1
            print(f"[{index + 1}/{call_count}] ERROR run_id={run_id} error={exc}")

    try:
        seeded_runs = recent_seeded_runs(client, project)
    except Exception as exc:
        seeded_runs = []
        print(f"Warning: unable to query recent seeded runs: {exc}")
    print("\nCompleted seeding observability runs.")
    print(f"Success: {success}")
    print(f"Failed : {failures}")
    seeded_count = len(seeded_runs)
    print(f"Recent seeded runs in last 30m (tag={SCRIPT_TAG}): {seeded_count}")
    print("Open dashboard and set project + Last 1 hour window in smith.langchain.com Monitoring.")
    return success, failures, seeded_count


def main() -> None:
    api_key = get_required_api_key()
    endpoint = os.getenv("LANGSMITH_ENDPOINT", DEFAULT_ENDPOINT)
    project = os.getenv("LANGSMITH_PROJECT", DEFAULT_PROJECT)
    model = os.getenv("OLLAMA_MODEL", DEFAULT_MODEL)
    api_url = os.getenv("OBS_INFERENCE_API_URL", DEFAULT_API_URL).rstrip("/")
    timeout_seconds = int(os.getenv("OBS_TIMEOUT_SECONDS", str(DEFAULT_TIMEOUT_SECONDS)))
    call_count = int(os.getenv("OBS_CALL_COUNT", str(DEFAULT_CALL_COUNT)))
    feedback_key = os.getenv("LANGSMITH_FEEDBACK_KEY", DEFAULT_FEEDBACK_KEY)
    prompts = load_prompts()

    client = Client(api_url=endpoint, api_key=api_key)
    print(f"LangSmith endpoint: {endpoint}")
    print(f"LangSmith project : {project}")
    print(f"Inference API URL : {api_url}")
    print(f"Model             : {model}")
    print(f"Calls             : {call_count}")
    print(f"Prompts loaded    : {len(prompts)}")

    seed_inference_runs(
        client=client,
        project=project,
        model=model,
        api_url=api_url,
        timeout_seconds=timeout_seconds,
        call_count=call_count,
        feedback_key=feedback_key,
        prompts=prompts,
    )


if __name__ == "__main__":
    main()
